export const CITATIONS_FETCH_STARTED = 'CITATIONS_FETCH_STARTED';
export const CITATIONS_FETCH_COMPLETED = 'CITATIONS_FETCH_COMPLETED';
export const CITATIONS_FETCH_FAILED = 'CITATIONS_FETCH_FAILED';

export const CITATION_ADD_STARTED = 'CITATION_ADD_STARTED';
export const CITATION_ADD_COMPLETED = 'CITATION_ADD_COMPLETED';
export const CITATION_ADD_FAILED = 'CITATION_ADD_FAILED';

export const CITATION_REMOVE_STARTED = 'CITATION_REMOVE_STARTED';
export const CITATION_REMOVE_COMPLETED = 'CITATION_REMOVE_COMPLETED';
export const CITATION_REMOVE_FAILED = 'CITATION_REMOVE_FAILED';