
export const EVENTS_FETCH_STARTED = 'EVENTS_FETCH_STARTED';
export const EVENTS_FETCH_COMPLETED = 'EVENTS_FETCH_COMPLETED';
export const EVENTS_FETCH_FAILED = 'EVENTS_FETCH_FAILED';

export const EVENT_ADD_STARTED = 'EVENT_ADD_STARTED';
export const EVENT_ADD_COMPLETED = 'EVENT_ADD_COMPLETED';
export const EVENT_ADD_FAILED = 'EVENT_ADD_FAILED';

export const EVENT_REMOVE_STARTED = 'EVENT_REMOVE_STARTED';
export const EVENT_REMOVE_COMPLETED = 'EVENT_REMOVE_COMPLETED';
export const EVENT_REMOVE_FAILED = 'EVENT_REMOVE_FAILED';