
export const POSTS_FETCH_STARTED = 'POSTS_FETCH_STARTED';
export const POSTS_FETCH_COMPLETED = 'POSTS_FETCH_COMPLETED';
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED';

export const POST_ADD_STARTED = 'POST_ADD_STARTED';
export const POST_ADD_COMPLETED = 'POST_ADD_COMPLETED';
export const POST_ADD_FAILED = 'POST_ADD_FAILED';

export const POST_REMOVE_STARTED = 'POST_REMOVE_STARTED';
export const POST_REMOVE_COMPLETED = 'POST_REMOVE_COMPLETED';
export const POST_REMOVE_FAILED = 'POST_REMOVE_FAILED';